GET http://localhost:8080/items/
Content-Type: application/json

{
  "username": "ehsandar"
}

###
POST http://localhost:8080/items/
Content-Type: application/json

{
  "username": "test 4"
}

###
GET http://localhost:8080/items/3/
Content-Type: application/json


###
PUT http://localhost:8080/items/2/
Content-Type: application/json

{
  "username": "man"
}

###
DELETE http://localhost:8080/items/1/
