### Item list
GET http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDg3NDE5NjIsImp0aSI6IjIiLCJpYXQiOjE2NDg0ODI3NjIsImlzcyI6ImRvcGFtaW5lIiwibmJmIjoxNjQ4NDgyNzYyLCJzdWIiOiJ7XCJVc2VySURcIjpcIjJcIixcIlN1cGVydXNlclwiOmZhbHNlLFwiUGVybWlzc2lvbnNcIjpbXCJjcmVhdGUtcG9zdHNcIl19In0.5leAsGzIDnJ9tvGwjdScDU9tAQVB2k_V1gDqPqW3Nds

###
POST http://localhost:8080/items/
Content-Type: application/json

{
  "username": "test 6"
}

###
GET http://localhost:8080/items/3/
Content-Type: application/json


###
PUT http://localhost:8080/items/6/
Content-Type: application/json

{
  "username": "test !"
}

###
DELETE http://localhost:8080/items/1/
